#!/usr/bin/env expect
set timeout 600

set files [glob -type f *]

spawn ftp
expect "ftp>" { send "open $env(FTP_HOST)\r" }
expect "Name*:" { send "$env(FTP_USERNAME)\r" }
expect "Password:" { send $env(FTP_PASSWORD)\r" }
expect "ftp>" { send "cd $env(FTP_PATH)/$env(FTP_DIRECTORY)\r" }
expect "ftp>" { send "prompt\r" }

foreach file $files {
  expect "ftp>" { send "put $file\r" }
  expect "ftp>" { send "get $file $file.fetched\r" }
}

expect "ftp>" { send "exit\r" }