drop function if exists setme(TEXT, TEXT);
drop function if exists getme(TEXT);
drop function if exists perl_warn(TEXT);
drop function if exists perl_elog(TEXT);
drop function if exists perl_spi_prepared_set(INTEGER, INTEGER);
drop function if exists perl_spi_prepared(INTEGER);
drop function if exists array_of_text();
drop function if exists recurse(INTEGER);
drop function if exists perl_spi_func();
drop function if exists perl_spi_func2();
drop function if exists perl_get_field(footype, TEXT);
drop function if exists foo_set_bad();
drop function if exists foo_bad();
drop function if exists foo_good();
drop function if exists perl_out_params_set();
drop function if exists perl_out_params();
drop function if exists perl_record_set();
drop function if exists perl_record();
drop function if exists perl_set();
drop function if exists perl_row();
drop function if exists perl_set_int(INTEGER);
drop function if exists perl_int(INTEGER);
