platform: linux
image_resource:
  type: docker-image

inputs:
  - name: gpdb_src
  - name: ccp_src
  - name: cluster_env_files
  - name: benchmark_data
outputs:
  - name: gpdb_artifacts

params:
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  TEST_BINARY_SWAP: false
  CONFIGURE_FLAGS: ""

run:
  path: gpdb_src/concourse/scripts/benchmark.bash
