platform: linux
inputs:
 - name: ccp_src
 - name: cluster_env_files
 - name: gpdb_binary
 - name: gpdb_src
run:
  path: bash
  args:
  - -c
  - |
    set -ex
    ccp_src/aws/setup_ssh_to_cluster.sh
    scp gpdb_binary/bin_gpdb.tar.gz mdw:/tmp
    ssh -t mdw bash -ex << EOF
        OPTIMIZER=${OPTIMIZER} \
        bash /home/gpadmin/gpdb_src/concourse/scripts/run_icw_ccp.sh
    EOF
