name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install depends
      run: ./README.ubuntu.bash
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make installcheck regress
      run: make -C src/test/regress installcheck-parallel
